### PR TITLE
Added four metabolites to minimal media files

### PR DESCRIPTION
**Pull request by tiekneeshrimp**
Resolves issue 14 on branch 18

### CODE REVIEW

**Comment by tiekneeshrimp** [comment]
*merging to main just to add to media files

**Comment by tiekneeshrimp** [comment]
Might merge to main regardless of failed checks--just to add to media files

**Comment by djinnome** [comment]
Interesting reason for the failed check.  I agree that we can probably separate the check failure into a separate PR.

**Review by mcnaughtonadm — APPROVED** [review]
The diff fail is saying that whatever model memote is using to check against the media doesn't have all the reactions in it. This is pulling the model that lives on `main` to do this. If we don't have the specific reactions in the model on `main` it could be the reason this is being returned.

I did some manual inspection of the main model and it looks like it has these reactions so not sure why the diff is complaining. Overall the diff is not critical to pass as the other reports are generated with the merge.

I agree we can override this for now.

**Pull request merged**
